/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 optimized-room.glb 
Author: Aleksei Rozumnyi (https://sketchfab.com/Aleksei.Rozumnyi)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tesla-semi-39ffc7c746184e0c9ebd5bbcd0b405dd
Title: Tesla Semi
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/optimized-room.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0, 0, 0.21]}>
          <group position={[-1.044, 0.677, -0.669]} rotation={[-Math.PI, 0, -Math.PI]}>
            <mesh geometry={nodes.Tires_0.geometry} material={materials.Tire_Material} />
            <mesh geometry={nodes.Disks002_0.geometry} material={materials.Disk_material} position={[-1.044, 2.385, 0.669]} />
            <mesh geometry={nodes.Disks001_0.geometry} material={materials.Disk_material} position={[-1.044, 3.314, 0.669]} />
            <mesh geometry={nodes.Disks_0.geometry} material={materials['Black_material.001']} position={[-1.044, -0.677, 0.669]} />
          </group>
          <mesh geometry={nodes.Truck_0.geometry} material={materials.Material} />
          <mesh geometry={nodes.Truck_1.geometry} material={materials.Glass} />
          <mesh geometry={nodes.Truck_2.geometry} material={materials.Lights} />
          <mesh geometry={nodes.Plane001_0.geometry} material={materials.Black_material} />
          <mesh geometry={nodes.Plane_0.geometry} material={materials.Sign} />
          <mesh geometry={nodes.Tires003_0.geometry} material={materials.Tire_Material} position={[-1.044, 3.74, -0.669]} rotation={[0, 0, -Math.PI]} />
          <mesh geometry={nodes.Tires002_0.geometry} material={materials.Tire_Material} position={[-1.044, 4.669, -0.669]} rotation={[0, 0, -Math.PI]} />
          <mesh geometry={nodes.Frame_0.geometry} material={materials.Black_material} />
          <mesh geometry={nodes.Handle_0.geometry} material={materials.TT_bake_node} position={[0, 3.833, -0.167]} rotation={[0, 0, -Math.PI]} />
          <mesh geometry={nodes.Tires005_0.geometry} material={materials.Tire_Material} position={[-1.044, 3.74, -0.669]} rotation={[0, 0, -Math.PI]} />
          <mesh geometry={nodes.Tires004_0.geometry} material={materials.Tire_Material} position={[-1.044, 4.669, -0.669]} rotation={[0, 0, -Math.PI]} />
          <mesh geometry={nodes.Bumper_0.geometry} material={materials.Black_material} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/optimized-room.glb')
